# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
#tasks:
#  - name: Script Task
#    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
#    command: echo 'start script'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
#ports:
#  - name: Frontend
#    description: Port 3000 for the frontend
#    port: 3000
#    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
image:
    file: .gitpod.Dockerfile

tasks:
  - init: pip3 install -r requeriments.txt
    command: python3 src/app.py

vscode:
    extensions:
        - almenon.arepl
        - littlefoxteam.vscode-python-test-adapter
        - ms-python.python